import { CategoriaProducto, UnidadProducto } from '../../modules/mercaderia/entities/producto.entity';

interface ProductoSeed {
  nombre: string;
  categoria: CategoriaProducto;
  unidad: UnidadProducto;
  orden: number;
  activo: boolean;
}

export const PRODUCTOS_SEED: ProductoSeed[] = [
  // ── Verduras y Hortalizas (30) ──────────────────────────────────
  { nombre: 'Tomate Redondo', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 1, activo: true },
  { nombre: 'Tomate Perita', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 2, activo: true },
  { nombre: 'Tomate Cherry', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 3, activo: true },
  { nombre: 'Papa Blanca', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 4, activo: true },
  { nombre: 'Papa Negra', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 5, activo: true },
  { nombre: 'Papa Andina', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 6, activo: true },
  { nombre: 'Cebolla', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 7, activo: true },
  { nombre: 'Cebolla Morada', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 8, activo: true },
  { nombre: 'Cebolla de Verdeo', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 9, activo: true },
  { nombre: 'Ajo', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 10, activo: true },
  { nombre: 'Zanahoria', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 11, activo: true },
  { nombre: 'Remolacha', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 12, activo: true },
  { nombre: 'Zapallo Criollo', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 13, activo: true },
  { nombre: 'Zapallo Anco', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 14, activo: true },
  { nombre: 'Berenjena', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 15, activo: true },
  { nombre: 'Morrón Rojo', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 16, activo: true },
  { nombre: 'Morrón Verde', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 17, activo: true },
  { nombre: 'Morrón Amarillo', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 18, activo: true },
  { nombre: 'Pepino', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 19, activo: true },
  { nombre: 'Choclo', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 20, activo: true },
  { nombre: 'Chauchas', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 21, activo: true },
  { nombre: 'Batata', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 22, activo: true },
  { nombre: 'Rabanito', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 23, activo: true },
  { nombre: 'Nabo', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 24, activo: true },
  { nombre: 'Alcaucil', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 25, activo: true },
  { nombre: 'Espárrago', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 26, activo: true },
  { nombre: 'Puerro', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 27, activo: true },
  { nombre: 'Apio', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 28, activo: true },
  { nombre: 'Brócoli', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 29, activo: true },
  { nombre: 'Coliflor', categoria: CategoriaProducto.VERDURAS_HORTALIZAS, unidad: UnidadProducto.KG, orden: 30, activo: true },

  // ── Frutas (25) ─────────────────────────────────────────────────
  { nombre: 'Manzana Roja', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 1, activo: true },
  { nombre: 'Manzana Verde', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 2, activo: true },
  { nombre: 'Manzana Fuji', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 3, activo: true },
  { nombre: 'Pera', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 4, activo: true },
  { nombre: 'Naranja', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 5, activo: true },
  { nombre: 'Mandarina', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 6, activo: true },
  { nombre: 'Limón', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 7, activo: true },
  { nombre: 'Pomelo', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 8, activo: true },
  { nombre: 'Banana', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 9, activo: true },
  { nombre: 'Frutilla', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 10, activo: true },
  { nombre: 'Durazno', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 11, activo: true },
  { nombre: 'Ciruela', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 12, activo: true },
  { nombre: 'Damasco', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 13, activo: true },
  { nombre: 'Melón', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 14, activo: true },
  { nombre: 'Sandía', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 15, activo: true },
  { nombre: 'Uva Negra', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 16, activo: true },
  { nombre: 'Uva Verde', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 17, activo: true },
  { nombre: 'Kiwi', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 18, activo: true },
  { nombre: 'Mango', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 19, activo: true },
  { nombre: 'Ananá', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 20, activo: true },
  { nombre: 'Palta', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 21, activo: true },
  { nombre: 'Granada', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 22, activo: true },
  { nombre: 'Higo', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 23, activo: true },
  { nombre: 'Arándano', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 24, activo: true },
  { nombre: 'Cereza', categoria: CategoriaProducto.FRUTAS, unidad: UnidadProducto.KG, orden: 25, activo: true },

  // ── Verduras de Hoja y Otros (22) ───────────────────────────────
  { nombre: 'Lechuga Mantecosa', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 1, activo: true },
  { nombre: 'Lechuga Criolla', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 2, activo: true },
  { nombre: 'Lechuga Morada', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 3, activo: true },
  { nombre: 'Lechuga Romana', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 4, activo: true },
  { nombre: 'Espinaca', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 5, activo: true },
  { nombre: 'Acelga', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 6, activo: true },
  { nombre: 'Rúcula', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 7, activo: true },
  { nombre: 'Perejil', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 8, activo: true },
  { nombre: 'Cilantro', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 9, activo: true },
  { nombre: 'Albahaca', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 10, activo: true },
  { nombre: 'Menta', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 11, activo: true },
  { nombre: 'Radicheta', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 12, activo: true },
  { nombre: 'Berro', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 13, activo: true },
  { nombre: 'Repollo Blanco', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 14, activo: true },
  { nombre: 'Repollo Morado', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 15, activo: true },
  { nombre: 'Kale', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 16, activo: true },
  { nombre: 'Hinojo', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 17, activo: true },
  { nombre: 'Ciboulette', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 18, activo: true },
  { nombre: 'Tomillo', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 19, activo: true },
  { nombre: 'Romero', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 20, activo: true },
  { nombre: 'Laurel Fresco', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 21, activo: true },
  { nombre: 'Orégano Fresco', categoria: CategoriaProducto.VERDURAS_HOJA, unidad: UnidadProducto.KG, orden: 22, activo: true },

  // ── Varios y Elaborados (20) ─────────────────────────────────────
  { nombre: 'Huevo', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.UNIDAD, orden: 1, activo: true },
  { nombre: 'Champiñones Blancos', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 2, activo: true },
  { nombre: 'Champiñones Portobello', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 3, activo: true },
  { nombre: 'Nuez', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 4, activo: true },
  { nombre: 'Almendras', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 5, activo: true },
  { nombre: 'Maní', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 6, activo: true },
  { nombre: 'Lima', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 7, activo: true },
  { nombre: 'Maracuyá', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 8, activo: true },
  { nombre: 'Mandioca', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 9, activo: true },
  { nombre: 'Jengibre', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 10, activo: true },
  { nombre: 'Frambuesa', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 11, activo: true },
  { nombre: 'Chirimoya', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 12, activo: true },
  { nombre: 'Ajíes Picantes', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 13, activo: true },
  { nombre: 'Cúrcuma', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 14, activo: true },
  { nombre: 'Zanahoria Baby', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 15, activo: true },
  { nombre: 'Mini Zucchini', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 16, activo: true },
  { nombre: 'Tomate Deshidratado', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 17, activo: true },
  { nombre: 'Pimiento Rojo Seco', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 18, activo: true },
  { nombre: 'Ajo en Bolsa', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 19, activo: true },
  { nombre: 'Ruibarbo', categoria: CategoriaProducto.VARIOS_ELABORADOS, unidad: UnidadProducto.KG, orden: 20, activo: true },
];
